defaults:
  - base: mhif
  - datasets_ytx
  - _self_

base:
  img_range: 1.0 # or adjust based on dataset_name
  debug: false
  test_samples_per_gpu: 1



log_epoch_interval: 1
train_log_iter_interval: 50
val_log_iter_interval: 10
test_log_iter_interval: 1
save_interval: 10


max_epochs: 2000
model_type: "SSRNet"
patch_size_list: { "lms": 64, "ms": 16, "pan": 64, "x_net": 64 }


optimizer_cfg:
  # see udl_vis.Basis.optim.optim.py
  optimizer_type: "adam"
  weight_decay: 0
  lr: 3e-4

scheduler_cfg: {}

# Evaluation
eval: false
direction: "maximize"


samples_per_gpu: 64
workers_per_gpu: 0
seed: 1
resume_from: ""
dataset:
  train_name: "cave_x4"
  val_name: "cave_x4"
  test_name: "cave_x4"

experimental_desc: "test"


args:
  # Model configuration
  model_path: ".pth.tar"
  use_resume: true
  resume_from: ""
  ms_channel: 3
  hs_channel: 31
  n_select_bands: 3
  scale: 4


  # Additional configuration
  workflow:
    - ["test", 1]
    - ["train", 10]


search_space:
  lr:
    method: suggest_categorical
    kwargs:
      name: "lr"
      # low: 0.0001
      # high: 0.01
      choices: [1e-3, 5e-4, 1e-4]
