defaults:
  - mhif
  - _self_

gpu_ids: [0]
launcher: "none" # options: none, pytorch, slurm, mpi, dp
local_rank: 0
log_epoch_interval: 1
train_log_iter_interval: 50
val_log_iter_interval: 10
test_log_iter_interval: 1
save_interval: 10
max_epochs: 2000
test_samples_per_gpu: 20
model_type: "bdt"
# dataset_type: "PanCollection" # "oldPan", "DLPan", "PanCollection", "Dummy"

args:
  # Experimental description
  experimental_desc: "test"

  # Model configuration
  model_path: ".pth.tar"
  use_resume: true
  resume_from: ""
  
  
  lr: 3e-4
  epochs: 2000
  samples_per_gpu: 32
  workers_per_gpu: 0

  # Dataset configuration
  # Evaluation
  eval: false



  # Additional configuration
  workflow:
    - ["test", 1]
    # - ["train", 10]


  img_range: 255.0 # or adjust based on dataset_name

search_space:
  lr:
    method: suggest_categorical
    kwargs:
      name: "lr"
      # low: 0.0001
      # high: 0.01
      choices: [1e-3, 5e-4, 1e-4]
